### ISSUE TITLE
Support yaml config files

### ISSUE THREAD

**Issue by TWilkin** [TWilkin/powerpi#373]
- They support comments, which would be really nice!
- They still support the json schema validation.
- Can just convert to JSON for emitting via the message queue so none of the other services need to know.
  - Can strip the comments (which will also get rid of the schema definition) which will make the message smaller.

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/TWilkin/powerpi/main/services/config-server/src/schema/config/devices.schema.json

devices:
- type: log
  name: Logger
  message: Howdy
  display_name: "Logger Device"
  categories:
  - Setup
  visible: true

# look a comment!
- type: condition
  name: Conditiony
  device: Logger
  on_condition:
    when:
    - equals: [ var: "message.state", "on" ]

sensors: []
```
