### ISSUE TITLE
Support sensors in UI using new metrics syntax

### ISSUE THREAD

**Issue by TWilkin** [TWilkin/powerpi#571]
Need to iterate over the metrics of a sensor (returned by the API) and display a sensor for each metric that is "visible".

For example in the new energy monitor sensor #554 the config is as follows:
```yaml
- type: zigbee_energy_monitor
  name: Sensor
  metrics:
    power: visible
    current: read
    voltage: read
```
