### ISSUE TITLE
Change custom sensor config syntax

### ISSUE THREAD

**Issue by TWilkin** [TWilkin/powerpi#572]
In #571 the UI will support the following metric syntax for sensors, this will allow the config for custom sensors to be simplified.

```yaml
- type: zigbee_energy_monitor
  name: Sensor
  metrics:
    power: visible
    current: read
    voltage: read
```

Suggesting to include temperature/humidity/motion as "metrics" and also support merging the polling config.
